os: linux
dist: bionic
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
services:
  - docker

before_install:
- pip install --upgrade pip
- pip install flake8  # find Python syntax errors and undefined names
- flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
install:
- scripts/setup-docker.sh

script:
- cd IBM_DB/ibm_db
- pip install .
#
# set up tests
- cp config.py.sample config.py
#
# These were deleted from git, but required by the tests
# we just create dummy files of the size expected
- truncate -s 10291 tests/spook.png
- truncate -s 15398 tests/pic1.jpg
#
# Create db2cli.ini
- echo -e '[sample]\nHostname=localhost\nProtocol=TCPIP\nDatabase=sample' > db2cli.ini
- export DB2CLIINIPATH=$PWD
#
# Run tests
- python tests.py

notifications:
  email:
    - skauser@rocketsoftware.com
